### ISSUE TITLE
panic: runtime error: index out of range [128] with length 128 on size = 6x7

### ISSUE THREAD

**Issue by shikharmishra1** [igrek51/connect4solver#2]
**Command:** 
```./c4solver --train --size 6x7```

**Output:**
```+-------------+
| . . . . . . |
| . . . . . . |
| . . . . . . |
| . . . . . . |
| . . . . . . |
| . . . . . . |
| . . . . . . |
+-------------+
| 0 1 2 3 4 5 |
t=2023-09-09T21:21:42+0530 lvl=dbug msg="Solver configured" boardWidth=6 boardHeight=7 winStreak=4 movesOrder="[3 2 4 1 5 0]" maxCacheDepth=38 maxCacheDepthSize=35714285
panic: runtime error: index out of range [128] with length 128

goroutine 1 [running]:
github.com/igrek51/connect4solver/solver/generic_solver.(*Referee).whoWonColumn(...)
        E:/repos/connect4solver/solver/generic_solver/referee.go:99
github.com/igrek51/connect4solver/solver/generic_solver.NewReferee(0xc00008a050)
        E:/repos/connect4solver/solver/generic_solver/referee.go:43 +0x567
github.com/igrek51/connect4solver/solver/generic_solver.NewMoveSolver(0xc00008a050)
        E:/repos/connect4solver/solver/generic_solver/solver.go:48 +0x5d3
github.com/igrek51/connect4solver/solver.CreateSolver(0xa1e160?)
        E:/repos/connect4solver/solver/solver_factory.go:15 +0x35
github.com/igrek51/connect4solver/solver.Train(0x6, 0x7, 0x4, 0x1)
        E:/repos/connect4solver/solver/train.go:16 +0x13d
main.main()
        E:/repos/connect4solver/main.go:28 +0x105
```

**Comment by igrek51** [comment]
@shikharmishra1  Thanks for finding this. Indeed, it was panicking due to hardcoded board height set to 6 in one place.
Now you can choose other board sizes, including `6x7`. Unfortunately, you can't go too far with it, cause I've made some low-level optimizations back then that keep column state in just one byte in memory, and due to that, you can't set height higher than 7.
Well, I could unlock that limit, but then the solver would work much slower (I've checked that).

**Comment by shikharmishra1** [comment]
Thank you so much for solving this! If it's not too much trouble, may I ask another question that's somewhat unrelated? I've noticed that many modern C4 games also feature blocker disks. I'm curious to know how difficult it might be to implement the functionality of blocker disks.

**Comment by igrek51** [comment]
I didn't know that rule before, sounds interesting. I'm afraid it would be quite hard to support it now since I've encoded column states with bits (0 is Player A, 1 is Player B). There's not much place for other types.
